/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlador;

import java.io.IOException;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.media.NoPlayerException;
import javax.media.CannotRealizeException;
import javax.media.MediaLocator;
import javax.media.Player;
import javax.media.Manager;
import javax.swing.ImageIcon;
import javax.swing.JToggleButton;
import java.awt.image.BufferedImage;
import java.util.Date;


public class WebCamForm extends javax.swing.JFrame {    
    Controlador conn = new Controlador();
    Arduino connArduino = new Arduino();
    CapturaImagem capturaImagem;
    Player player;
    String nfile;
    BufferedImage bi;

    public WebCamForm() {
        initComponents();
        try {
            initCamera();
        } catch (IOException ex) {
            Logger.getLogger(WebCamForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoPlayerException ex) {
            Logger.getLogger(WebCamForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CannotRealizeException ex) {
            Logger.getLogger(WebCamForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void initCamera() throws IOException, NoPlayerException, CannotRealizeException {
         
        MediaLocator m1 = new MediaLocator("vfw://0");
        player = Manager.createRealizedPlayer(m1);
        this.tbcamera.add(player.getVisualComponent());
        player.start();
        System.out.println("");

    }

    private void setImageButton(JToggleButton tbutton, Image image) {
        tbutton.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tbcamera = new javax.swing.JToggleButton();
        bCapture = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBLeft = new javax.swing.JButton();
        JTextGraus = new javax.swing.JTextField();
        jBDown = new javax.swing.JButton();
        jBUp = new javax.swing.JButton();
        jBRight = new javax.swing.JButton();
        jBClose = new javax.swing.JButton();
        jBCameraON = new javax.swing.JButton();
        jBCameraOFF = new javax.swing.JButton();
        jBResetpt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PROJETO LEONA");

        bCapture.setText("Capture");
        bCapture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCaptureMouseClicked(evt);
            }
        });
        bCapture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCaptureActionPerformed(evt);
            }
        });

        bSave.setText("Stop");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText(" Rede Colaborativa na América Latina para a Investigação de ELTe EAE de Tempestades");

        jBLeft.setText("LEFT");
        jBLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBLeftMouseClicked(evt);
            }
        });
        jBLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLeftActionPerformed(evt);
            }
        });

        JTextGraus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextGrausActionPerformed(evt);
            }
        });

        jBDown.setText("DOWN");
        jBDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBDownMouseClicked(evt);
            }
        });
        jBDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDownActionPerformed(evt);
            }
        });

        jBUp.setText("UP");
        jBUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBUpMouseClicked(evt);
            }
        });
        jBUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUpActionPerformed(evt);
            }
        });

        jBRight.setText("RIGHT");
        jBRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBRightMouseClicked(evt);
            }
        });
        jBRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRightActionPerformed(evt);
            }
        });

        jBClose.setText("Sair");
        jBClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCloseMouseClicked(evt);
            }
        });

        jBCameraON.setText("Camera ON");
        jBCameraON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCameraONMouseClicked(evt);
            }
        });

        jBCameraOFF.setText("Camera OFF");
        jBCameraOFF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCameraOFFMouseClicked(evt);
            }
        });

        jBResetpt.setText("Reset");
        jBResetpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBResetptMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(tbcamera, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jBResetpt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBClose, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(bSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bCapture, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBCameraOFF, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBCameraON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(482, 482, 482)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(408, 408, 408)
                        .addComponent(jBLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBDown)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(JTextGraus)
                                    .addComponent(jBUp, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBRight))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBResetpt)
                        .addGap(109, 109, 109)
                        .addComponent(jBCameraON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBCameraOFF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addComponent(bCapture, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bSave))
                    .addComponent(tbcamera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBRight)
                        .addComponent(jBLeft))
                    .addComponent(JTextGraus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBDown)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCaptureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCaptureActionPerformed
        String diretorio = "C:/ProjetoLeona/Observações/";
        String observacao = "Evento ";

         if ("Capture".equals(evt.getActionCommand())) {
             capturaImagem = new CapturaImagem(diretorio, observacao, this);              
             capturaImagem.start();
         }
          else{
               if ("Stop".equals(evt.getActionCommand())) {
                  System.out.println("**************Cancela de capturar imagens**********");
            }
         }
   
    }//GEN-LAST:event_bCaptureActionPerformed

    private void dateTime() {
        Date date = new Date(System.currentTimeMillis());
        System.out.println(new Date());
        System.out.println("Data" + date);

    }


    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        System.out.println("********************************parar de tirar fotos*******************************");
         capturaImagem.stop();
    }//GEN-LAST:event_bSaveActionPerformed

    private void bCaptureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCaptureMouseClicked
         // TODO add your handling code here:        
    }//GEN-LAST:event_bCaptureMouseClicked

    private void jBLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLeftMouseClicked

        String graus = String.valueOf(JTextGraus.getText());
        connArduino.comunicacaoArduino(jBLeft, graus);
    }//GEN-LAST:event_jBLeftMouseClicked

    private void jBLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBLeftActionPerformed

    private void JTextGrausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextGrausActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextGrausActionPerformed

    private void jBDownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBDownMouseClicked

        String graus = String.valueOf(JTextGraus.getText());
        connArduino.comunicacaoArduino(jBDown, graus);
    }//GEN-LAST:event_jBDownMouseClicked

    private void jBDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBDownActionPerformed

    private void jBUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBUpMouseClicked

        String graus = String.valueOf(JTextGraus.getText());
        connArduino.comunicacaoArduino(jBUp, graus);
    }//GEN-LAST:event_jBUpMouseClicked

    private void jBUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBUpActionPerformed

    private void jBRightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBRightMouseClicked

        String graus = String.valueOf(JTextGraus.getText());
        connArduino.comunicacaoArduino(jBRight, graus);
    }//GEN-LAST:event_jBRightMouseClicked

    private void jBRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBRightActionPerformed

    private void jBCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCloseMouseClicked

        String graus = String.valueOf(JTextGraus.getText());
        connArduino.comunicacaoArduino(jBClose, graus);

        System.exit(0);//fecha a aplicação
    }//GEN-LAST:event_jBCloseMouseClicked

    private void jBCameraONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCameraONMouseClicked
        String graus = String.valueOf(JTextGraus.getText());
        connArduino.comunicacaoArduino(jBCameraON, graus);
    }//GEN-LAST:event_jBCameraONMouseClicked

    private void jBCameraOFFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCameraOFFMouseClicked

        String graus = String.valueOf(JTextGraus.getText());
        connArduino.comunicacaoArduino(jBCameraOFF, graus);
    }//GEN-LAST:event_jBCameraOFFMouseClicked

    private void jBResetptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBResetptMouseClicked
        String graus = String.valueOf(JTextGraus.getText());
        connArduino.comunicacaoArduino(jBResetpt, graus);
    }//GEN-LAST:event_jBResetptMouseClicked

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WebCamForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextGraus;
    private javax.swing.JButton bCapture;
    private javax.swing.JButton bSave;
    private javax.swing.JButton jBCameraOFF;
    private javax.swing.JButton jBCameraON;
    private javax.swing.JButton jBClose;
    private javax.swing.JButton jBDown;
    private javax.swing.JButton jBLeft;
    private javax.swing.JButton jBResetpt;
    private javax.swing.JButton jBRight;
    private javax.swing.JButton jBUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton tbcamera;
    // End of variables declaration//GEN-END:variables
}
